# name: Solar System Workflow

# on: 
#   workflow_dispatch:
#   push:
#     branches:
#       - main
#       - 'feature/*'
    
# jobs:
#     unit-testing:
#         name: Unit Testing
#         runs-on: ubuntu-latest
#         steps:
#         - name: Checkout Repository
#           uses: actions/checkout@v4

#         - name: Setup NodeJS Version
#           uses: actions/setup-node@v3
#           with:
#             node-version: 20
    
#         - name: Install Dependencies
#           run: npm install
    
#         - name: Unit Testing
#           run: npm test
          
#         - name: Archive Test Result
#           uses: actions/upload-artifact@v3
#           with:
#             name: Mocha-Test-Result
#             path: test-results.xml


name: solar system workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: superuser
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
  
jobs:
  unit-testing:
    name: unit testing
    services:
      mongo-db:
        image: siddarth67/mongo-db:non-prod
        ports:
          - 27017:27017
    env:
      MONGO_URI: 'mongodb://localhost:27017/superData'
      MONGO_USERNAME: superuser
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    strategy:
          matrix:
            nodejs_version: [18,20]
            operating_system: [ ubuntu-latest]
            exclude:
              - nodejs_version: 18
                operating_system: macos-latest
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup nodejs version - 20
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache Primes
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{hashFiles('package-lock.json')}}

      - name: install dependencies
        run: npm install

      - name: unit testing
        id: nodejs-unit-testing-step
        run: npm test

      - name: Archive Test Result
        if: always()
        # if: failure() && (steps.nodejs-unit-testing-step == 'failure' || steps.nodejs-unit-testing-step == 'success')
        uses: actions/upload-artifact@v4  
        with:
          name: Mocha-Test-Result
          path: test-01-results.xml

  code-coverage:
    name: code coverage
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup node js version - 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache Primes
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{hashFiles('package-lock.json')}}

      - name: install dependencies
        run: npm install

      - name: check code coverage
        continue-on-error: true
        run: npm run coverage
        
      - name: archive test result
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-result
          path: coverage
          
  docker:
    name: containerization
    needs: [ unit-testing,code-coverage ]
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      
      - name: dockerhub login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD}}

      # - name: GHCR Login
      #   uses: docker/login-action@v2.2.0
      #   with:
      #     registry: ghcr.io
          
      #     username: ${{ github.repository_owner }}
      #     password: ${{secrets.USER_TOKEN}}

      - name: Docker Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: vijayasharma582/solar-system


      - name: Docker image testing
        run: |
          docker images
          docker run --name solar-system-app -d -p 3000:3000 -e MONGO_URI=$MONGO_URI -e MONGO_USERNAME=$MONGO_USERNAME -e MONGO_PASSWORD=$MONGO_PASSWORD vijayasharma582/solar-system
          export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}'solar-system-app)
          echo $IP
          echo Testing image url using wget
          wget -q -O - 127.0.0.1:3000/live | grep live

      # - name: Docker Build 
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     push: true
      #     tags: vijayasharma582/solar-system
      
      # - name: container registry push
      #   uses: docker/build-push-action@v6
      #   with:
      #     context:
      #     push: true
      #     tags: |
      #       ghcr.io/vijayasharma582/solar-system      